export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "React Dev",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "Next Dev",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "Ninja Tech",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "Kungfu Panda",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "React Lover",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpeg",
    username: "Tech Savy",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "Mr. Dev",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "Dev Lobster",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "NoCode noReact",
  },
];

export const postData = [
  {
    id: 1,
    desc: "I learned Next.js",
    photo: "assets/post/1.jpeg",
    timestamp: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "Omg! Next 13 just released",
    timestamp: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "My frontend skills",
    photo: "assets/post/3.jpeg",
    timestamp: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    timestamp: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    timestamp: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    timestamp: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "guys, please check out my new projects",
    photo: "assets/post/7.jpeg",
    timestamp: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    timestamp: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Can anyone help me with React router dom?",
    photo: "assets/post/9.jpeg",
    timestamp: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    timestamp: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
